### ISSUE TITLE
ipv6  Still experiencing power outages

### ISSUE THREAD

**Issue by fayejun** [joe97tab/PI-Pwn-Offline#1]
Hello author, I really like your work. It's easy and fast to use. But after my testing, it still loses power when using IPv6. Tested with the cursed model, regardless of whether C++is selected as stooged or feng, the cursed model still loses power after selecting IPv6. Normal models can be used normally. I have tested with Stooged's code alone, and the cursed model will not power off, while testing with your IPv6 system will indeed power off. I hope to have some free time to solve this problem and see where the error lies. Thank you.

**Comment by fayejun** [comment]
What I want to express is that using your code to create a box, even if IPv6 is selected, cursed models will still power off. Every time there is a power outage, and various combination schemes have been tested to ensure that it will be disconnected.

**Comment by joe97tab** [comment]
I have no idea why IPv6 address will effect power consumption.
Stooged binary and xfangfang binary, in term of performance should be the same.
If you experienced the problem please use xfangfang binary, set CPPMETHOD="3".

Shutdown problem, edit run.sh script by change this line

sudo poweroff

to

sudo shutdown -P now
