### ISSUE TITLE
HI,there i use it on onecloud (s805）but eth0 is shutdown and don't up，when i click the force pwn buton

### ISSUE THREAD

**Issue by cpa341** [joe97tab/PI-Pwn-Offline#3]
tty1 shown: Ready for console connection,then do noting,eth0 is shutdown and don't up.

**Comment by joe97tab** [comment]
1. Check your network config.
/etc/interfaces/network

auto eth0
iface eth0 inet manual
up ip link set eth0 promisc on
down ip link set eth0 promisc off

2. Check network manager

/etc/NetworkManager/NetworkManager.conf

[main]
dns=none
rc-manager=unmanaged
plugins=ifupdown,keyfile

[ifupdown]
managed=false 

3. Some device may look it work but it actually not work, try to change to new dtb.
